
JFILES = ProducerConsumer.java\
		Producer.java\
		Consumer.java\
		Buffer.java
MISC = makefile\
		README.txt

all:
	javac $(JFILES)
clean:
	rm *.class

submission:
	tar -cvf Westerman_Christopher_HW5.tar $(JFILES)
